TICKET-62-RELEASE
sanjayguwaju/team-blog-app-frontend pull request #52
Opened 2023-09-25 13:21 UTC by Kushalbaj

2023-09-25 15:26 UTC, sanjayguwaju requested changes
please made the changes

2023-09-25 15:26 UTC, sanjayguwaju commented on src/components/BlogPost.jsx
> +  console.log("ShowTrimmedPost ~~~~~~~~~~~>", showTrimmedPost)
remove this line 6 console.log

2023-09-25 15:26 UTC, sanjayguwaju commented on src/components/BlogPost.jsx
> +        {console.log("kkkkkkkkkkkkkkkk",showTrimmedPost)}
remove the conosole.log

2023-09-25 15:26 UTC, sanjayguwaju commented on src/pages/Homepage.jsx
> +    // console.log("showTrimmedPost ~~~~~~~~~~~>",showTrimmedPost)
remove this comment

2023-09-25 17:27 UTC, Kushalbaj commented on src/components/BlogPost.jsx
> +  console.log("ShowTrimmedPost ~~~~~~~~~~~>", showTrimmedPost)
REMOVED

2023-09-25 17:27 UTC, Kushalbaj commented on src/components/BlogPost.jsx
> +        {console.log("kkkkkkkkkkkkkkkk",showTrimmedPost)}
REMOVED

2023-09-25 17:28 UTC, Kushalbaj commented on src/pages/Homepage.jsx
> +    // console.log("showTrimmedPost ~~~~~~~~~~~>",showTrimmedPost)
REMOVED

2023-09-26 02:56 UTC, sanjayguwaju approved these changes

2023-09-27 07:30 UTC, closed without merging